### ISSUE TITLE
Box doesn't work

### ISSUE THREAD

**Issue by beathorst** [martin-helmich/typo3-ci-example#2]
The Box is not existing anymore

```
config.vm.box = "chef/debian-7.4"
```

**Comment by beathorst** [comment]
I want to open the TYPO3-Site in my Browser. how can I do this? IP-Adresse?

**Comment by martin-helmich** [comment]
Thanks for the hint, I'll replace the image on occasion.

In the long run, I'm planning to switch to a Docker based solution anyways.

Am 05.11.2015 um 09:59 schrieb Janek Rüßmann:
